const inter = Inter({ subsets: ["latin"] });
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import AuthProvider from "@/providers/AuthProvider";
import { StoreProvider } from "@/redux/StoreProvider";

export const metadata = {
  title: "Amazon Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children,isAdminPage }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <StoreProvider>
          {!isAdminPage && <Header />}
            {children}
          </StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
